import { generateHttpTests } from '../src/generateHttpTests';
import fs from 'node:fs';

export default async function setup() {
  // Only generate tests if they don't exist (CLI generates them)
  // This allows CLI to generate tests with any spec, and Jest won't overwrite them
  const testFile = 'tests/generated.http.spec.ts';
  if (!fs.existsSync(testFile)) {
    // Fallback: generate from default spec if tests don't exist
    await generateHttpTests('samples/petstore.yaml', testFile);
  }
  // If tests already exist (generated by CLI), don't overwrite them
}
